name: 'GitLab Stats'

on:
  schedule:
    - cron: '0 0 * * *' # runs every day at midnight
  workflow_dispatch: # allows manual triggering of the workflow

jobs:
  update:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Set up Go'
        uses: 'actions/setup-go@v2'
        with:
          go-version: '1.20'

      - name: 'Get GitLab Stats'
        env:
          GITLAB_TOKEN: '${{ secrets.GITLAB_TOKEN }}'
          GITLAB_USERNAME: '${{ secrets.GITLAB_USERNAME }}'
        run: |
          go run main.go

      - name: 'Commit and Push'
        run: |
          git config --global user.name 'GitLab Stats Workflow'
          git config --global user.email 'rios0rios0@outlook.com'
          git add . && git commit -m "Deploy to GitHub Pages" --amend --no-edit
          git push -f origin HEAD:gitlab-stats
